export type FacturaCompra = {
  id: string;
  visibleId: string;
  proveedorId: string | null;
  proveedor: { id: string; nombre: string } | null;
  razonSocial: string;
  cuit: string | null;
  tipo: "A" | "B" | "C" | "TICKET" | "RECIBO";
  numero: string;
  puntoVenta: string | null;
  fecha: Date;
  vencimiento: Date | null;
  subtotal: number;
  iva21: number;
  iva105: number;
  iva27: number;
  percepcionIVA: number;
  percepcionIIBB: number;
  impInterno: number;
  noGravado: number;
  exento: number;
  total: number;
  categoria: "MANTENIMIENTO" | "COMBUSTIBLE" | "SEGURO" | "PATENTE" | "REPUESTOS" | "ALQUILER_LOCAL" | "SERVICIOS" | "SUELDOS" | "MARKETING" | "IMPUESTOS" | "GRUA" | "ADMINISTRATIVO" | "OTRO";
  subcategoria: string | null;
  centroGasto: string | null;
  motoId: string | null;
  moto: { id: string; marca: string; modelo: string; patente: string } | null;
  estado: "PENDIENTE" | "PAGADA" | "PAGADA_PARCIAL" | "VENCIDA" | "ANULADA";
  montoAbonado: number;
  archivoUrl: string | null;
  archivoNombre: string | null;
  ocrRawData: unknown | null;
  ocrConfianza: number | null;
  ocrRevisado: boolean;
  gastoId: string | null;
  asientoId: string | null;
  notas: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type FacturaCompraFormData = {
  proveedorId?: string | null;
  razonSocial: string;
  cuit?: string;
  tipo: "A" | "B" | "C" | "TICKET" | "RECIBO";
  numero: string;
  puntoVenta?: string;
  fecha: string;
  vencimiento?: string;
  subtotal: number;
  iva21: number;
  iva105: number;
  iva27: number;
  percepcionIVA: number;
  percepcionIIBB: number;
  impInterno: number;
  noGravado: number;
  exento: number;
  categoria: "MANTENIMIENTO" | "COMBUSTIBLE" | "SEGURO" | "PATENTE" | "REPUESTOS" | "ALQUILER_LOCAL" | "SERVICIOS" | "SUELDOS" | "MARKETING" | "IMPUESTOS" | "GRUA" | "ADMINISTRATIVO" | "OTRO";
  subcategoria?: string;
  centroGasto?: string;
  motoId?: string | null;
  estado: "PENDIENTE" | "PAGADA" | "PAGADA_PARCIAL" | "VENCIDA" | "ANULADA";
  montoAbonado: number;
  archivoUrl?: string;
  archivoNombre?: string;
  notas?: string;
};

export type OCRResponse = {
  success: boolean;
  data: {
    razonSocial: string;
    cuit?: string;
    tipo: "A" | "B" | "C" | "TICKET" | "RECIBO";
    numero: string;
    puntoVenta?: string;
    fecha: string;
    vencimiento?: string;
    subtotal: number;
    iva21: number;
    iva105: number;
    iva27: number;
    percepcionIVA: number;
    percepcionIIBB: number;
    impInterno: number;
    noGravado: number;
    exento: number;
    total: number;
    confianza: number;
    notas?: string;
  };
};
